import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";

import Nav from "../components/Nav";
import Filters from "../components/Filters";
import Actions from "../components/Actions";

import { FiSearch } from "react-icons/fi";
import { GrClose } from "react-icons/gr";
import { GoSettings } from "react-icons/go";
import { AiFillLinkedin, AiOutlineTwitter } from "react-icons/ai";

import styles from "../styles/Home.module.css";

export default function Home() {
  const [results, setResults] = useState([]);
  const [showFilters, setShowFilters] = useState(false);
  const [showActions, setShowActions] = useState(false);

  useEffect(() => {
    const width = window.innerWidth;

    if (width > 992) {
      setShowFilters(true);
      setShowActions(true);
    } else if (width < 991 && width > 600) {
      setShowFilters(false);
      setShowActions(true);
    } else {
      setShowFilters(false);
      setShowActions(false);
    }
  });

  const handleShowFilters = () => {
    // setShowFilters(!showFilters);
  };

  const handleShowActions = () => {
    // setShowActions(!showActions);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Blog-Search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo_blue.png" />
      </Head>

      <main className={styles.main}>
        <Nav />
        <div
          className={styles.content}
          style={
            showFilters
              ? {}
              : showActions
              ? {
                  gridTemplateColumns: "0fr 2.5fr 1fr",
                  gridTemplateAreas: "content content actions",
                }
              : {
                  gridTemplateColumns: "0fr 3fr 0fr",
                  gridTemplateAreas: "content content content",
                  padding: 0,
                  gridGap: 0,
                }
          }
        >
          <Filters
            showFilters={showFilters}
            handleShowFilters={handleShowFilters}
          />
          <div className={styles.blogs}>
            <div className={styles.top}>
              {showFilters ? (
                <></>
              ) : (
                <div
                  className={styles.filters}
                  style={{ width: showActions ? "8%" : "15%" }}
                >
                  <GoSettings
                    className={styles.icon}
                    // style={{ margin: showActions ? "0 5px" : "0 2px" }}
                  />
                </div>
              )}
              <div
                className={styles.search}
                style={{
                  width: showActions ? "100%" : "70%",
                  padding: showActions ? "0 10px" : "0 5px",
                }}
              >
                <FiSearch
                  className={styles.icon}
                  // style={{ margin: showActions ? "0 5px" : "0 2px" }}
                />
                <input
                  type="text"
                  placeholder="Search here..."
                  className={styles.search_input}
                />
                <GrClose className={styles.icon} />
              </div>
              {showActions ? (
                <></>
              ) : (
                <div
                  className={styles.actions}
                  style={{ width: showActions ? "8%" : "15%" }}
                >
                  <p className={styles.icon}>A</p>
                </div>
              )}
            </div>
            <div className={styles.results}>
              {results.length > 0 ? (
                <></>
              ) : (
                <div className={styles.big_logo}>
                  <Image
                    src="/logo_blue.png"
                    width="150"
                    height="150"
                    alt="logo"
                  />
                </div>
              )}
            </div>
          </div>
          <Actions
            showActions={showActions}
            handleShowActions={handleShowActions}
          />
        </div>
      </main>

      <footer className={styles.footer}>
        <div className={styles.logo}>
          <Image src="/logo_white.png" width="28" height="28" alt="logo" />
          <p>BlogSearch</p>
        </div>
        <div className={styles.links}>
          <div className={styles.resources}>
            <p className={styles.title}>Resources</p>
            <ul>
              <li>Home</li>
              <li>Directory</li>
              <li>Blog Rankings</li>
              <li>Best Posts</li>
              <li>Submit Blog</li>
              <li>API</li>
              <li>Data</li>
              <li>About</li>
            </ul>
          </div>
          <div className={styles.socials}>
            <p className={styles.title}>Follow us</p>
            <ul>
              <li>
                <AiFillLinkedin className={styles.icon} />
                <p>LInkedIn</p>
              </li>
              <li>
                <AiOutlineTwitter className={styles.icon} />
                <p>Twitter</p>
              </li>
            </ul>
          </div>
        </div>
      </footer>
    </div>
  );
}
