import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";

import Nav from "../components/Nav";
import Filters from "../components/Filters";
import Actions from "../components/Actions";

import axios from "axios";
import { FiSearch } from "react-icons/fi";
import { GrClose } from "react-icons/gr";
import { GoSettings } from "react-icons/go";
import { AiFillLinkedin, AiOutlineTwitter } from "react-icons/ai";

import styles from "../styles/Home.module.css";
import Blogs from "../components/Blogs";
import Pagination from "../components/Pagination";

export default function Home() {
  const [results, setResults] = useState([]);
  const [currentPage, setCurrentPage] = useState(1);
  const [blogsPerPage, setblogsPerPage] = useState(7);
  const [width, setWidth] = useState(0);
  const [search, setSearch] = useState("");

  const [showFilters, setShowFilters] = useState(false);
  const [showActions, setShowActions] = useState(false);

  const indexOfLastBlog = currentPage * blogsPerPage;
  const indexOfFirstBlog = indexOfLastBlog - blogsPerPage;
  const currentBlogs = results?.slice(indexOfFirstBlog, indexOfLastBlog);

  useEffect(() => {
    const width = window.innerWidth;
    setWidth(width);
    console.log(width);

    if (width > 992) {
      setShowFilters(true);
      setShowActions(true);
    } else if (width < 992 && width > 600) {
      setShowFilters(false);
      setShowActions(true);
    } else {
      setShowFilters(false);
      setShowActions(false);
    }
  }, [width]);

  const handleShowFilters = () => {
    // setShowFilters(!showFilters);
  };

  const handleShowActions = () => {
    // setShowActions(!showActions);
  };

  const paginate = (pageNumber) => {
    setCurrentPage(pageNumber);
  };

  const handleSearch = async (e) => {
    setSearch(e.target.value);

    await fetch(`/api/${e.target.value}`)
      .then((res) => res.json())
      .then((data) => {
        setResults(data?.blogs?.results[0]?.hits);
      });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Blog-Search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo_blue.png" />
      </Head>

      <main className={styles.main}>
        <Nav />
        <div
          className={styles.content}
          style={
            showFilters
              ? {}
              : showActions
              ? {
                  gridTemplateColumns: "0fr 2.5fr 1fr",
                  gridTemplateAreas: "content content actions",
                }
              : {
                  gridTemplateColumns: "0fr 3fr 0fr",
                  gridTemplateAreas: "content content content",
                  padding: 0,
                  gridGap: 0,
                }
          }
        >
          <Filters
            showFilters={showFilters}
            handleShowFilters={handleShowFilters}
          />
          <div className={styles.blogs}>
            <div className={styles.top}>
              {showFilters ? (
                <></>
              ) : (
                <div
                  className={styles.filters}
                  style={{ width: showActions ? "8%" : "15%" }}
                >
                  <GoSettings
                    className={styles.icon}
                    // style={{ margin: showActions ? "0 5px" : "0 2px" }}
                  />
                </div>
              )}
              <div
                className={styles.search}
                style={{
                  width: showActions ? "100%" : "70%",
                  padding: showActions ? "0 10px" : "0 5px",
                }}
              >
                <FiSearch
                  className={styles.icon}
                  // style={{ margin: showActions ? "0 5px" : "0 2px" }}
                />
                <input
                  type="text"
                  placeholder="Search here..."
                  className={styles.search_input}
                  value={search}
                  onChange={handleSearch}
                />
                <GrClose className={styles.icon} />
              </div>
              {showActions ? (
                <></>
              ) : (
                <div
                  className={styles.actions}
                  style={{ width: showActions ? "8%" : "15%" }}
                >
                  <p className={styles.icon}>A</p>
                </div>
              )}
            </div>
            <div className={styles.results}>
              {results.length > 0 ? (
                <div className={styles.div}>
                  <div className={styles.header}>
                    <p>{results?.length} Results</p>
                    <select name="sort">
                      <option value="Relevance">Relevance</option>
                      <option value="Category">Category</option>
                    </select>
                  </div>
                  <Blogs blogs={currentBlogs} width={width} />
                  <Pagination
                    blogsPerPage={blogsPerPage}
                    totalBlogs={results.length}
                    currentPage={currentPage}
                    paginate={paginate}
                  />
                </div>
              ) : (
                <div className={styles.big_logo}>
                  <Image
                    src="/logo_blue.png"
                    width="150"
                    height="150"
                    alt="logo"
                  />
                </div>
              )}
            </div>
          </div>
          <Actions
            showActions={showActions}
            handleShowActions={handleShowActions}
          />
        </div>
      </main>

      <footer className={styles.footer}>
        <div className={styles.logo}>
          <Image src="/logo_white.png" width="28" height="28" alt="logo" />
          <p>BlogSearch</p>
        </div>
        <div className={styles.links}>
          <div className={styles.resources}>
            <p className={styles.title}>Resources</p>
            <ul>
              <li>Home</li>
              <li>Directory</li>
              <li>Blog Rankings</li>
              <li>Best Posts</li>
              <li>Submit Blog</li>
              <li>API</li>
              <li>Data</li>
              <li>About</li>
            </ul>
          </div>
          <div className={styles.socials}>
            <p className={styles.title}>Follow us</p>
            <ul>
              <li>
                <AiFillLinkedin className={styles.icon} />
                <p>LInkedIn</p>
              </li>
              <li>
                <AiOutlineTwitter className={styles.icon} />
                <p>Twitter</p>
              </li>
            </ul>
          </div>
        </div>
      </footer>
    </div>
  );
}
